import 'package:movieshop/src/models/paliculas.dart';

List<Pelicula> getPeliculas() {
  return [
    new Pelicula(1, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(2, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
    new Pelicula(3, "Intrépido", "Animado","Un joven gamer debe convertirse en canguro a tiempo completo cuando su videojuego favorito deja a tres niños pequeños con superpoderes en su jardín.", "3.jpg", "f3.jpg"),
    new Pelicula(4, "High Score","Acción", "Esta docuserie recorre la historia de los videojuegos clásicos con la participación de quienes, con sus ideas innovadoras, dieron vida a estos mundos y personajes.", "4.jpg", "f4.jpg"),
    new Pelicula(5, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(6, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
    new Pelicula(7, "Intrépido", "Animado","Un joven gamer debe convertirse en canguro a tiempo completo cuando su videojuego favorito deja a tres niños pequeños con superpoderes en su jardín.", "3.jpg", "f3.jpg"),
    new Pelicula(8, "High Score","Acción", "Esta docuserie recorre la historia de los videojuegos clásicos con la participación de quienes, con sus ideas innovadoras, dieron vida a estos mundos y personajes.", "4.jpg", "f4.jpg"),
    new Pelicula(9, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(10, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
    new Pelicula(11, "Intrépido", "Animado","Un joven gamer debe convertirse en canguro a tiempo completo cuando su videojuego favorito deja a tres niños pequeños con superpoderes en su jardín.", "3.jpg", "f3.jpg"),
    new Pelicula(12, "High Score","Acción", "Esta docuserie recorre la historia de los videojuegos clásicos con la participación de quienes, con sus ideas innovadoras, dieron vida a estos mundos y personajes.", "4.jpg", "f4.jpg"),
    new Pelicula(13, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(14, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
    new Pelicula(15, "Intrépido", "Animado","Un joven gamer debe convertirse en canguro a tiempo completo cuando su videojuego favorito deja a tres niños pequeños con superpoderes en su jardín.", "3.jpg", "f3.jpg"),
    new Pelicula(16, "High Score","Acción", "Esta docuserie recorre la historia de los videojuegos clásicos con la participación de quienes, con sus ideas innovadoras, dieron vida a estos mundos y personajes.", "4.jpg", "f4.jpg"),
    new Pelicula(17, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(18, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
    new Pelicula(19, "Intrépido", "Animado","Un joven gamer debe convertirse en canguro a tiempo completo cuando su videojuego favorito deja a tres niños pequeños con superpoderes en su jardín.", "3.jpg", "f3.jpg"),
    new Pelicula(20, "High Score","Acción", "Esta docuserie recorre la historia de los videojuegos clásicos con la participación de quienes, con sus ideas innovadoras, dieron vida a estos mundos y personajes.", "4.jpg", "f4.jpg"),
    new Pelicula(21, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(22, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
    new Pelicula(23, "Intrépido", "Animado","Un joven gamer debe convertirse en canguro a tiempo completo cuando su videojuego favorito deja a tres niños pequeños con superpoderes en su jardín.", "3.jpg", "f3.jpg"),
    new Pelicula(24, "High Score","Acción", "Esta docuserie recorre la historia de los videojuegos clásicos con la participación de quienes, con sus ideas innovadoras, dieron vida a estos mundos y personajes.", "4.jpg", "f4.jpg"),
    new Pelicula(25, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(26, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
    new Pelicula(27, "Intrépido", "Animado","Un joven gamer debe convertirse en canguro a tiempo completo cuando su videojuego favorito deja a tres niños pequeños con superpoderes en su jardín.", "3.jpg", "f3.jpg"),
    new Pelicula(28, "High Score","Acción", "Esta docuserie recorre la historia de los videojuegos clásicos con la participación de quienes, con sus ideas innovadoras, dieron vida a estos mundos y personajes.", "4.jpg", "f4.jpg"),
    new Pelicula(29, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
  
  ];
}

List<Pelicula> getPeliculasRecientes() {
  return [
   new Pelicula(1, "¡Scooby!","Animado", "Con cientos de casos resueltos y aventuras compartidas, Scooby y la pandilla se enfrentan al misterio más grande y desafiante de todos los tiempos: un complot para liberar al perro fantasma Cerberus en el mundo. Mientras compiten para detener esta escasez de perros global, la pandilla descubre que Scooby tiene un legado secreto y un destino épico más grande de lo que cualquiera podría haber imaginado.", "1.jpg", "f1.jpg"),
    new Pelicula(2, "Lucifer","Terror", "La serie se centrará en Lucifer (Tom Ellis) quien, aburrido e infeliz como el Señor del Infierno, dimite de su trono y abandona su reino para trasladarse a la ciudad de Los Angeles y abrir un lujoso piano-bar llamado Lux. Una vez allí ayudará a la policía a castigar a los más peligrosos criminales de la ciudad.", "2.jpg", "f2.jpg"),
  ];
}